# Generated by Django 4.2.7 on 2023-11-30 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desktop_image', models.ImageField(upload_to='images/desktop')),
                ('mobile_image', models.ImageField(upload_to='images/mobile')),
                ('alt_text', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Home Page Image',
                'verbose_name_plural': 'Home Page Images',
                'ordering': ['title'],
            },
        ),
    ]
