# Generated by Django 4.2.7 on 2023-12-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avrupada_karavan', '0002_blogpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleImagePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/single')),
                ('alt_text', models.CharField(max_length=255)),
            ],
        ),
    ]
