# Generated by Django 4.2.7 on 2023-12-04 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avrupada_karavan', '0003_singleimagepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('founded_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mileage', models.IntegerField(help_text='in kilometers')),
                ('transmission', models.CharField(max_length=100)),
                ('registration_date', models.DateField()),
                ('power', models.CharField(help_text='in kW (horsepower)', max_length=50)),
                ('fuel_type', models.CharField(max_length=50)),
                ('number_of_owners', models.IntegerField(default=1)),
                ('permissible_gross_weight', models.IntegerField(help_text='in kilograms')),
                ('HU', models.DateField(blank=True, null=True)),
                ('air_conditioning', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('axles', models.IntegerField(default=2)),
                ('number_of_sleeping_places', models.IntegerField(default=2)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='avrupada_karavan.brand')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='avrupada_karavan.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
