# Generated by Django 4.2.7 on 2023-12-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avrupada_karavan', '0005_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='Production'),
        ),
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(default='Production', max_length=250),
        ),
    ]
