# Generated by Django 4.2.7 on 2023-12-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avrupada_karavan', '0006_product_description_product_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
