# Generated by Django 4.2.7 on 2023-12-08 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avrupada_karavan', '0009_contactform'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
