# Generated by Django 4.2.7 on 2023-12-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avrupada_karavan', '0012_staticpage_footermenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPageInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('tel', models.CharField(max_length=255)),
                ('whatsapp', models.CharField(max_length=255)),
                ('facebook_url', models.CharField(max_length=255)),
                ('instagram_url', models.CharField(max_length=255)),
                ('twitter_url', models.CharField(max_length=255)),
            ],
        ),
    ]
